//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using EVMData;
using Newtonsoft.Json;
using System;


namespace EVM {
    
    
    // #주의 ITableData는 자동 생성되지 않습니다. 자동 생성된 코드를 사용 전 미리 정의가 필요합니다.
    [System.Serializable()]
    public class BoxTableData : ITableData {
        
        [JsonProperty()]
        private int index;
        
        [JsonProperty()]
        private BoxType box_type;
        
        [JsonProperty()]
        private int selectbox_num;
        
        [JsonProperty()]
        private OpenQualificationType open_qualification_type;
        
        [JsonProperty()]
        private int open_qualification_value;
        
        [JsonProperty()]
        private string open_qualification_language_key;
        
        [JsonProperty()]
        private int reward_group_id;
        
        [JsonProperty()]
        private string language_title;
        
        [JsonProperty()]
        private string language_des;
        
        [JsonProperty()]
        private string box_thumbnail;
        
        [JsonProperty()]
        private string language_badge;
        
        // 박스의 타입
        public BoxType BoxType {
            get {
                return this.box_type;
            }
        }
        
        // Select 아이템 선택 개수
        public int SelectboxNum {
            get {
                return this.selectbox_num;
            }
        }
        
        // 상자 오픈 조건
        public OpenQualificationType OpenQualificationType {
            get {
                return this.open_qualification_type;
            }
        }
        
        // 상자 오픈 조건 세부 값
        public int OpenQualificationValue {
            get {
                return this.open_qualification_value;
            }
        }
        
        // 상자 오픈 조건 설명 텍스트
        public string OpenQualificationLanguageKey {
            get {
                return this.open_qualification_language_key;
            }
        }
        
        // 지급 보상 그룹
        public int RewardGroupId {
            get {
                return this.reward_group_id;
            }
        }
        
        // 박스 이름 텍스트
        public string LanguageTitle {
            get {
                return this.language_title;
            }
        }
        
        // 박스 설명 텍스트
        public string LanguageDes {
            get {
                return this.language_des;
            }
        }
        
        // 박스  썸네일
        public string BoxThumbnail {
            get {
                return this.box_thumbnail;
            }
        }
        
        // 뱃지 텍스트
        public string LanguageBadge {
            get {
                return this.language_badge;
            }
        }
        
        // 테이블의 index를 ITableData Interface의 Property를 재정의함.
        public int Index {
            get {
                return this.index;
            }
        }
        
        public override string ToString() {
            System.Text.StringBuilder stringBuilder = new System.Text.StringBuilder();
            stringBuilder.AppendLine($"object Name= BoxTableData");
            stringBuilder.AppendLine($"index= {index}");
            stringBuilder.AppendLine($"box_type= {box_type}");
            stringBuilder.AppendLine($"selectbox_num= {selectbox_num}");
            stringBuilder.AppendLine($"open_qualification_type= {open_qualification_type}");
            stringBuilder.AppendLine($"open_qualification_value= {open_qualification_value}");
            stringBuilder.AppendLine($"open_qualification_language_key= {open_qualification_language_key}");
            stringBuilder.AppendLine($"reward_group_id= {reward_group_id}");
            stringBuilder.AppendLine($"language_title= {language_title}");
            stringBuilder.AppendLine($"language_des= {language_des}");
            stringBuilder.AppendLine($"box_thumbnail= {box_thumbnail}");
            stringBuilder.AppendLine($"language_badge= {language_badge}");
            return stringBuilder.ToString();
        }
    }
}
